/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_HelloJni */

#ifndef _Included_filterLib
#define _Included_filterLib
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *, void *);

JNIEXPORT void JNICALL Java_org_kineticsfoundation_lib_FilterLibrary_process(
		JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
